### PR TITLE
Slight optimization for Mash's battles

### PR DESCRIPTION
**Pull request by birdievera**
Hi! I hope you don't mind my participation in helping out on #2. I've optimized the first Mash battle so that there are only two attack sequences rather than three (as the result of picking a buster attack first). The rest of the battles unfortunately can't be optimized to end quicker. 

Also wanted to say that your re-roller is quite impressive. Thanks a lot!

### CODE REVIEW

**Comment by nisegami** [comment]
Thank you for doing this! I was so busy working on v4 (hint: check that branch out) that I never got around to making this change.

**Comment by birdievera** [comment]
Those are some good changes in v4! Memu restarting will be a huge lifesaver. VPN capabilities are nice too. I just hope you're enjoying yourself while coding since it is a lot to implement.

**Comment by nisegami** [comment]
Coding is actually in and of itself the primary reason I'm doing this. Having another project for GitHub/resume, helping others by sharing it and rerolling for nice accounts are all nice too, but I think my main reason is that I enjoy coding a lot.

**Comment by birdievera** [comment]
It's great to see someone so passionate about it!

(On a sidenote, the novel you wrote is pretty darn good too)

**Pull request merged**
